version: "3.8"
services:
  sniproxy:
    image: lancachenet/sniproxy:latest
    container_name: sniproxy
    restart: unless-stopped
    network_mode: host
    command: ["/usr/sbin/sniproxy","-f","-c","/etc/sniproxy.conf"]
    volumes:
      - ./sniproxy.conf:/etc/sniproxy.conf
